version: '3'

networks:
  proxy:
    external: true

services:
  lisaherradi:
    image: zero-site-2:latest
    ports:
      - "83:80"
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.89.1.3
